package generate_model

//
var templateStr = `
// Code generated by table_data_compare . DO NOT EDIT.

package tab_models

import (
	{{- range .ImportPath}}
	"{{.}}"
	{{- end}}
)

func init() {
	t1 := new({{.TableStructName}})
	tablePool[t1.TableName()] = t1
}


{{.TableStructDef}}


func (l *{{.TableStructName}}) RecordList() interface{} {
	return &[]*{{.TableStructName}}{}
}

func (l *{{.TableStructName}}) Record() interface{} {
	return &{{.TableStructName}}{}
}

//PkList() interface{}
//PkName,
func (l *{{.TableStructName}}) PkName() string {
	return "{{.PkColumnName}}"
}


`
