
// Code generated by table_data_compare . DO NOT EDIT.

package tab_models

import (
	"time"
)

func init() {
	t1 := new(UserInfo)
	tablePool[t1.TableName()] = t1
}


type UserInfo struct {
	ID              int64     `gorm:"column:id;primary_key;AUTO_INCREMENT"` // 用户ID
	Username        string    `gorm:"column:username;NOT NULL"`
	Nickname        string    `gorm:"column:nickname;NOT NULL"`
	ProfilePhotoUrl string    `gorm:"column:profile_photo_url"`
	Email           string    `gorm:"column:email;NOT NULL"`
	Password        string    `gorm:"column:password"`
	UserStatus      int       `gorm:"column:user_status"`
	FollowerCnt     int       `gorm:"column:follower_cnt;default:0;NOT NULL"`
	Ctime           time.Time `gorm:"column:ctime;default:CURRENT_TIMESTAMP;NOT NULL"` // 创建时间
	Mtime           time.Time `gorm:"column:mtime;default:CURRENT_TIMESTAMP;NOT NULL"` // 最后修改时间
	TestMax         string    `gorm:"column:test_max"`
}

func (m *UserInfo) TableName() string {
	return "user_info"
}



func (l *UserInfo) RecordList() interface{} {
	return &[]*UserInfo{}
}

func (l *UserInfo) Record() interface{} {
	return &UserInfo{}
}

//PkList() interface{}
//PkName,
func (l *UserInfo) PkName() string {
	return "id"
}


